Food/urls.py
from django.urls import path
from .import views

#namespacing
app_name = "Food"

urlpatterns = [
    #/food
    path('', views.index,name ="index"),
    # path('', views.IndexClassView.as_view(),name ="index"),
    # #/food/1
    #  path('<int:item_id>', views.detail,name ="detail"),
     path('<int:pk>', views.FoodDetail.as_view(),name ="detail"),
     #add
    #  path('add', views.create_item,name ="create_item"),

     path('add', views.CreateItem.as_view(),name ="create_item"),
     #edit
     path('update/<int:id>', views.update_item,name ="update_item"),
      #delete
     path('delete/<int:id>', views.delete_item,name ="delete_item"),
]

FoodHub/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Food/', include('Food.urls')),
     path('users/', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as authentication_views

urlpatterns = [
     path('register/',views.register,name="register" ),
     path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name="login"),
     path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name="logout"),
     path('profile/',views.profilePage,name="profile" ),
]

Food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://assets.materialup.com/uploads/b03b23aa-aa69-4657-aa5e-fa5fef2c76e8/preview.png")

    def __str__(self):
        return self.item_name

    ######for class based view 
    def get_absolute_url(self):
        return reverse("Food:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    image = models.ImageField(default="profilepic.jpg",upload_to="profile_picture")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

Food/forms.py
from  django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = "__all__"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

Food/views.py
from django.shortcuts import render,redirect
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    return render(request,"Food/index.html",{"item_list":item_list})

######Class Based View
class IndexClassView(ListView):
    model = Item
    template_name = "Food/index.html"
    context_object_name = 'item_list'

def detail(request,item_id):
    item= Item.objects.get(pk=item_id)
    return render(request,"Food/detail.html",{"item":item})

class FoodDetail(DetailView):
    model = Item
    template_name = "Food/detail.html"
    
def create_item(request):
    form =ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("Food:index")
    return render(request,"Food/form.html",{"form":form})

####Class Based View

class CreateItem(CreateView):
    model = Item
    fields = ["item_name","item_desc","item_price","item_image"]
    template_name = "Food/form.html"

    def form_valid(self,form):
        form.instance.user_name =self.request.user
        return super().form_valid(form) 
        
def update_item(request,id):
    item = Item.objects.get(id=id)
    form =ItemForm(request.POST or None,instance=item)
    #inorder to item be present before update instance=item
    if form.is_valid():
        form.save()
        return redirect("Food:index")
    return render(request,"Food/form.html",{"form":form,"item":item})

def delete_item(request,id):
    item = Item.objects.get(id=id)
    if request.method == "POST":
        item.delete()
        return redirect("Food:index")
    return render(request,"Food/delete.html",{"item":item})

    

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm

from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if(request.method=='POST'):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username} you are logged in')
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request,"users/register.html",{"form":form})

@login_required
def profilePage(request):
    return render(request,"users/profile.html")

Food/templates/Food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodHub</title>
    <link rel="stylesheet" href="{% static 'Food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar  -->
    <nav class="navbar navbar-dark bg-dark">
      <a href="#" class="navbar-banner">FoodHub</a>
      <div class="navbar">
          <a href="{% url 'Food:create_item'%}" class="nav-item nav-link">Add Item</a>
          <a href="#" class="nav-item nav-link">View Item</a>
          <a href="#" class="nav-item nav-link">Delete Item</a>

          {% if user.is_authenticated %}
           <a href="{% url 'logout' %}">Logout</a>
           <a href="{% url 'profile' %}">Profile</a>
        {%else%}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    {% if messages %}
    {% for message in messages%}
    <div class="alert alert-{{message.tags }}">
    {{message}}
</div>
    {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
</body>
</html>

Food/templates/Food/delete.html
<form method="POST" class="mt-2">
    {% csrf_token %}
   <h2>Are you sure you want to delete {{item.item_name}}</h2> 
    <button type="submit">Confirm</button>
</form>

Food/templates/Food/detail.html
{% extends "Food/base.html"%} {% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img height="300px" src="{{item.item_image}}" class="card" />
    </div>
    <div class="col-md-6">
      <h1>{{item.item_name}}</h1>
      <h1>{{item.item_desc}}</h1>
      <h1>₹{{item.item_price}}</h1>

      <!-- For class Based view -->

      <!-- <h1>{{object.item_name}}</h1>
      <h1>{{object.item_desc}}</h1>
      <h1>₹{{object.item_price}}</h1> -->
      <a href="{% url 'Food:delete_item' item.id %}">Delete</a>
    </div>
  </div>
</div>
{% endblock %}

Food/templates/Food/form.html
{% extends "Food/base.html"%} {% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-success text-white">
          <div class="card-title">Add Item</div>
        </div>
        <div class="card-body">
          <form method="POST">
            {%csrf_token%} {{form}}
            <br />
            <button class="btn-success" type="submit">Add</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Food/templates/Food/index.html
{% extends "Food/base.html"%} {% block body %} {% for item in item_list %}
<div class="row">
  <div class="col-md-3 offset-md-2">
    <img class="card" src="{{ item.item_image }}" height="150px" />
  </div>
  <div class="col-md-4">
    <h3>{{item.item_name}}</h3>
    <h5>{{item.item_desc}}</h5>
    <h6>₹{{item.item_price}}</h6>
    <h6>{{item.user_name}}</h6>
  </div>
  <div class="col-md-2">
    <a href="{% url 'Food:detail' item.id %}" class="btn btn-success"
      >Details</a
    >
  </div>
</div>
{% endfor %} {% endblock %}

users/templates/users/login.html
{% extends "Food/base.html"%} {% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-success text-white">
          <div class="card-title">Login</div>
        </div>
        <div class="card-body">
          <form method="POST">
            {%csrf_token%} {% for field in form %}
            <div class="form-group mb-3">{{field.name}} {{field}}</div>
            {% endfor %}
            <button class="btn-success" type="submit">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

users/templates/users/logout.html
<h1>You have been logged out </h1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{ user.profile.image.url }}" alt="pic" />

users/templates/users/register.html
{% extends "Food/base.html"%} {% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-success text-white">
          <div class="card-title">Register</div>
        </div>
        <div class="card-body">
          <form method="POST">
            {%csrf_token%} {% for field in form %}
            <div class="form-group">
              {{field.name}}
              <br />
              {{field}}
            </div>
            {% endfor %}
            <button class="btn-success mt-3" type="submit">Signup</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}